package snake.mcmods.theinvoker.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

// Date: 2013/5/25 2:08:05
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

public class ModelTotem extends ModelBase
{
    // fields
    ModelRenderer stick_h;
    ModelRenderer flag_back;
    ModelRenderer stick_v;
    ModelRenderer flag_f;

    public ModelTotem()
    {
        textureWidth = 64;
        textureHeight = 32;

        stick_h = new ModelRenderer(this, 12, 0);
        stick_h.addBox(-6F, -1.5F, -1.5F, 12, 3, 3);
        stick_h.setRotationPoint(0F, 4F, 0F);
        stick_h.setTextureSize(64, 32);
        stick_h.mirror = true;
        setRotation(stick_h, 0F, 0F, 0F);
        
        flag_back = new ModelRenderer(this, 12, 6);
        flag_back.addBox(-6F, 0F, 0F, 12, 22, 0);
        flag_back.setRotationPoint(0F, 2F, 1.7F);
        flag_back.setTextureSize(64, 32);
        flag_back.mirror = true;
        setRotation(flag_back, 0F, 0F, 0F);
        flag_back.mirror = false;
        
        stick_v = new ModelRenderer(this, 0, 0);
        stick_v.addBox(-1.5F, -23F, -1.5F, 3, 24, 3);
        stick_v.setRotationPoint(0F, 24F, 0F);
        stick_v.setTextureSize(64, 32);
        stick_v.mirror = true;
        setRotation(stick_v, 0F, 0F, 0F);
        
        flag_f = new ModelRenderer(this, 12, 6);
        flag_f.addBox(-6F, 0F, 0F, 12, 22, 0);
        flag_f.setRotationPoint(0F, 2F, -1.7F);
        flag_f.setTextureSize(64, 32);
        flag_f.mirror = true;
        setRotation(flag_f, 0F, 0F, 0F);
    }

    public void render(Entity par1Entity, float par2, float par3, float par4, float par5,
            float par6, float par7)
    {
        super.render(par1Entity, par2, par3, par4, par5, par6, par7);
        setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
        stick_h.render(par7);
        flag_back.render(par7);
        stick_v.render(par7);
        flag_f.render(par7);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float par1, float par2, float par3, float par4, float par5,
            float par6, Entity par7Entity)
    {
        super.setRotationAngles(par1, par2, par3, par4, par5, par6, par7Entity);
    }
    
    public void render()
    {
        stick_h.render(0.0625F);
        flag_back.render(0.0625F);
        stick_v.render(0.0625F);
        flag_f.render(0.0625F);
    }
}
